export type enrollment = {
    class_batch: string,
  class_finish_date: string,
  class_id: string,
  class_location:string,
  class_name: string,
  class_name_with_link: string,
  class_start_date:string,
  completed_at_utc: string,
  course_code: string,
  credits: string,
  final_grade:string,
  final_grade_message: string,
  now_utc: string,
  organization_id: string,
  organization_name:string,
  section_code: string,
  site_name: string,
  site_name_with_url: string,
  student_id: string,
  teacher_name: string,
  teacher_name_with_link: string,
  user_email: string,
  user_first_name: string,
  user_full_name: string,
  user_full_name_with_link: string,
  user_id: string,
  user_last_name: string,
  user_notes: string,
  user_program_end_date: string,
  user_program_name: string,
  user_program_start_date: string,
  user_transcript_print_date: string,
  userid: string,
  visit_the_class: string,
  why: string
}